### ISSUE TITLE
Question about NatSQL data generation

### ISSUE THREAD

**Issue by JuruoMP** [ygan/NatSQL#2]
Hi. I'm interested in your NatSQL, and i find that you provide your NatSQL queries under NatSQLv1_6/.
Could you please demonstrate how to convert them or share the script on converting original SQLs into NatSQLs?

**Comment by Sm1Ling** [comment]
Also interested in this

**Comment by rajkrishnamondal** [comment]
I am also interested, how it generates NatSQL queries under NatSQLv1_6/.

**Comment by ygan** [comment]
Sorry. We have not completed the SQL2NatSQL conversion code at present. We welcome contributions to NatSQL.

**Comment by rajkrishnamondal** [comment]
Sure I am interested.
