### ISSUE TITLE
Inner imports problem

### ISSUE THREAD

**Issue by Sm1Ling** [ygan/NatSQL#3]
Probably it worth rewriting inner code imports in relative format

For instance
NatSQL/natsql2sql/natsql2sql.py:
`
from natsql2sql.preprocess.stemmer import MyStemmer
`
turn to
`
from .preprocess.stemmer import MyStemmer
`

And 

NatSQL/natsql2sql/preprocess/stemmer.py:
`
from natsql2sql.preprocess.match import ALL_JJS
`
turn to
`
from .match import ALL_JJS
`

And so on.

For example, using this repo in GoogleColab inflicts importing errors

**Comment by ygan** [comment]
Thanks for your comments. We have updated it.
